/// Flutter icons ChessIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/

library;

import 'package:flutter/widgets.dart';

class ChessIcons {
  ChessIcons._();

  static const _kFontFam = 'ChessIcons';
  static const String? _kFontPkg = null;

  static const IconData chessBishop =
      IconData(0xf43a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chessKing =
      IconData(0xf43f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chessKnight =
      IconData(0xf441, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chessPawn =
      IconData(0xf443, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chessQueen =
      IconData(0xf445, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chessRook =
      IconData(0xf447, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
